/// Generated by AssetsRefGenerator on 2022/04/20
class Res {
  static const String happy = "assets/images/happy.svg";
  static const String heart = "assets/images/heart.svg";
  static const String sad = "assets/images/sad.svg";
}
